Renamed constants
ICTU/ictuwp-plugin-conference pull request #19
Opened 2023-02-09 13:36 UTC by paulvanbuuren

2023-02-09 13:48 UTC, davidhund approved these changes
@paulvanbuuren — ik heb dit niet (lokaal) functioneel getest, maar het ziet er goed uit. Versie is (goed) bijgewerkt, dus we moeten mogelijk een nieuwe versie requiren in de NPR. Dat zal ik doen indien nodig.

Vraag: willen we deze constants dupliceren naar GC constants.php?

2023-02-09 13:48 UTC, davidhund commented on ictuwp-plugin-conference.php
> +define( 'ICTU_GC_CONF_VERSION', '2.5.1' );
Deze willen we niet hernoemen?

2023-02-09 13:49 UTC, davidhund commented on ictuwp-plugin-conference.php
> +define( 'ICTU_GC_CONF_VERSION', '2.5.1' );
Het zijn/lijken wel erg 'private' constants, dus wellicht niet nodig..

2023-02-09 13:51 UTC, davidhund requested changes
@paulvanbuuren zag in de comments dat het ging om een Taxonomy, maar de constants zijn _CPT genoemd...

2023-02-09 13:51 UTC, davidhund commented on ictuwp-plugin-conference.php
> +if ( ! defined( 'GC_CONF_SPEAKER_CPT' ) ) {
@paulvanbuuren zie ik net: is dit een _taxonomy_? Dan zou het `_TAX` moeten zijn ipv `_CPT`

2023-02-09 13:51 UTC, davidhund commented on ictuwp-plugin-conference.php
> +if ( ! defined( 'GC_CONF_SESSION_CPT' ) ) {
@paulvanbuuren zie ik net: is dit een _taxonomy_? Dan zou het `_TAX` moeten zijn ipv `_CPT`

2023-02-09 13:54 UTC, davidhund requested changes

2023-02-09 14:05 UTC, paulvanbuuren commented on ictuwp-plugin-conference.php
> +if ( ! defined( 'GC_CONF_SPEAKER_CPT' ) ) {
de comments kloppen niet, wegens verregaande koppie-peest.

2023-02-10 11:31 UTC, davidhund approved these changes
Topperr! 🍌
PS: ik heb deze ook alvast toegevoegd aan: https://github.com/ICTU/ictuwp-gebruikercentraal/pull/261/files#diff-1f438d4cdc2e99de361b30bfd0a782e94e6791f408b1de92f7503f9c5d5851ff

Merge away!

2023-02-10 11:52 UTC, merged